NeurodataWithoutBorders/nwbwidgets

- nwbwidgets/image.py
- nwbwidgets/view.py
Fixes #3 
Example output (can be reproduced with instructions in https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/issues/3#issuecomment-492796444):
@mgrauer @lydiang
> Add image.show_index_series

- nwbwidgets/image.py
- nwbwidgets/view.py
Fixes #5 
Example (can be reproduced with https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/issues/3#issuecomment-492796444):
@mgrauer @lydiang
> Add image.show_grayscale_image

- examples/YutaMouse41.ipynb
- examples/allen_ecephys_session_785402239.ipynb
- nwbwidgets/base.py
- nwbwidgets/behavior.py
- nwbwidgets/ecephys.py
- nwbwidgets/view.py
fix #7 
allow vis specs passed to nwb2widget to be preserved through the recursion.
> vis spec no longer global

- .gitignore
> add a gitignore

- examples/allen_ecephys_session_785402239.ipynb
> example interactive table for allen data

- nwbwidgets/misc.py
* add psth evaluation
* update compute_smoothed_firing_rate
> Add psth evaluation function

- nwbwidgets/spectrum.py
- nwbwidgets/view.py
added widget to handle ndx-spectrum `Spectrum` datatype
could you try testing : 
```python
from pynwb import NWBHDF5IO
from nwbwidgets import nwb2widget
from IPython.display import display
io = NWBHDF5IO(r"ibl_eid.nwb", mode='r', load_namespaces=True)
nwb = io.read()
a=nwb2widget(nwb)
```
ibl_eid.nwb here https://drive.google.com/file/d/1MF3uitbMxvxpQtGYqE-gr1eNrA2AZc_i/view?usp=sharing
dataset: processing>ephys>_iblqc_ephysSpectralDensity
> add spectrum widget

- nwbwidgets/ophys.py
the image_mask plots of the ROIs now show the ROI id label on hover
> add roi ids as labels

- nwbwidgets/controllers/misc.py
- nwbwidgets/ophys.py
this PR adds a progress bar while loading image_masks of planesegmentation table.
> progress bar add

- nwbwidgets/controllers/misc.py
- nwbwidgets/ophys.py
the old merged PR #142 , after last commit https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/pull/142/commits/71340222d283fd32e72d0e499a16ed96b8cdb9d7: in which the button+bar were grouped in a HBox widget, ends up removing the drop down selection widget also. This PR fixes that.
> Progressbar ophys

- nwbwidgets/image.py
- nwbwidgets/ophys.py
adds a plotly widget to viz the 2photon series images
> adding 2p plotly traces

- nwbwidgets/version.py
> Next version

- .gitignore
- nwbwidgets/misc.py
> Merge widgets

- nwbwidgets/controllers/group_and_sort_controllers.py
- nwbwidgets/test/test_timeseries.py
- nwbwidgets/timeseries.py
- nwbwidgets/utils/plotly.py
using webgl for plotting multitrace plots
> use webgl in plotly.py

- nwbwidgets/behavior.py
- nwbwidgets/test/test_behavior.py
- nwbwidgets/test/test_controllers.py
- nwbwidgets/timeseries.py
- nwbwidgets/view.py
> window control for spatial traces

- nwbwidgets/test/test_timeseries.py
- nwbwidgets/timeseries.py
update `show_index_timeseries_plotly()` and its usage in `SingleTracePlotlyWidget `and `SeparateTracesPlotlyWidget`
> updating plotly function to show timeseries

- nwbwidgets/ophys.py
- nwbwidgets/test/test_ophys.py
> refactor ophys tests

- nwbwidgets/controllers/misc.py
- nwbwidgets/misc.py
- nwbwidgets/test/test_misc.py
- nwbwidgets/utils/units.py
- nwbwidgets/utils/widgets.py
- `TrialEventController` as a `SelectMultiple` to allow to select more alignment times
- The `PSTHWidget.update()` function handles subplots based on multiple selection
@bendichter  I think that this implementaiton is easier than extending the `PSTHWidget` class. The drawback is that `start_time` and `stop_time` are the same for multiple alignments.
> Extend PSTH to plot multiple alignments

- nwbwidgets/icephys.py
- nwbwidgets/utils/timeseries.py
- nwbwidgets/view.py
- test/test_icephys.py
> I-V curve widget for Icephys table

- nwbwidgets/icephys.py
> fix iv curve

- nwbwidgets/allen.py
- nwbwidgets/analysis/spikes.py
- nwbwidgets/brains.py
- nwbwidgets/icephys.py
- nwbwidgets/image.py
- nwbwidgets/misc.py
- nwbwidgets/ophys.py
- nwbwidgets/timeseries.py
- nwbwidgets/utils/dynamictable.py
This PR has some maintenance updates I encountered from running the tests. 
Contents:
- The first commit is specifically fixing local deprecation warnings flagged raised by the test suite to make things more future proof. 
- The second commit is a sweep of some small updates from running a linter (small refactors, and removing a few unused lines.
> [MNT] - Fix up deprecation warnings + lints

- nwbwidgets/panel.py
- requirements.txt
this depends on the next release of pynwb with fsspec
> add fsspec as stream mode

- docs/source/conf.py
- docs/source/contents/neurodata_widgets.md
- docs/source/contents/neurodata_widgets/behavior.rst
- docs/source/contents/neurodata_widgets/ecephys.rst
- docs/source/contents/neurodata_widgets/file.rst
- docs/source/contents/neurodata_widgets/icephys.rst
- docs/source/contents/neurodata_widgets/index.rst
- docs/source/contents/neurodata_widgets/ophys.rst
- docs/source/index.rst
* separate docs into modules
* formal links to autogen API of this library and of pynwb
> modularize docs

- nwbwidgets/ophys.py
- test/test_ophys.py
fix #236 
* fix show_plane_segmentation_2d for many categories
* add test
> fix show_plane_segmentation_2d for many categories

- .pre-commit-config.yaml
- pyproject.toml
@bendichter Initial setup for enabling pre-commit. Once this is on main I can turn the bot on and then go through the other PRs to fix any conflicts
> Add pre commit configs

- .github/workflows/workflow.yml
Simple daily CRON schedule for tests
Let's us know if new package releases break things ASAP
Also might play a role in keeping coverage reports up to date
> Run tests on schedule

- nwbwidgets/panel.py
- requirements.txt
Fetches dandisets metadata faster using multithreading
> Faster fetch dandisets

- nwbwidgets/utils/dandi.py
removing the subject name at the beginning the file path for the dropdown items actually broke the file fetching step... my bad
> hotfix - full file path
